### ISSUE TITLE
[istio-beacon-k8s] istio-beacon's authorizationpolicy for the modeloperator does not work

### ISSUE THREAD

**Issue by ca-scribner** [canonical/service-mesh#714]
### Bug Description

In canonical/istio-beacon-k8s-operator#46 we added an `AuthorizationPolicy` that allowed all traffic to the modeloperator in beacon's model.  This looked roughly like:

```yaml
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  labels:
    app.juju.is/created-by: istio-beacon-k8s
    app.kubernetes.io/instance: istio-beacon-k8s-test-charm-bcdk
    kubernetes-resource-handler-scope: istio-authorization-policy
  name: istio-beacon-k8s-test-charm-bcdk-policy-all-sources-modeloperator
  namespace: test-charm-bcdk
spec:
  rules:
  - {}
  selector:
    matchLabels:
      operator.juju.is/name: modeloperator
```

This targets the modeloperator workload via a workload selector.  

Currently in Juju 3.6.6, our `test_modeloperator_rule` CI which asserts this is working is failing.  I see the modeloperator pod does not have the `{operator.juju.is/name: modeloperator}` label anymore, and instead has `{juju-modeloperator: modeloperator}`.  This means the AuthorizationPolicy does nothing, and beacon's policies block traffic to the modeloperator.  This is confirmed by looking at the ztunnel logs, which show communication being rejected by absence of an allow policy.

I'm not sure when this change in Juju occurred, but I'm guessing in a recent-ish Juju (3.6.x?) this label has been changed.  

We should do a few things to address this:
* fix this bug.  should we support the old labeling scheme, or just assume people have a new-enough Juju to have the new scheme?
* make an issue/proposal on what we should change to catch this proactively.  We shouldn't notice this by accident after Juju has released it.  Since we're relying on implementation details in juju like this label, we may need more proactive testing of pre-release candidates to catch any regressions early
  * ✅ https://github.com/canonical/service-mesh/issues/715

### To Reproduce

Run the CI in juju 3.6.6

### Environment

juju 3.6.6

### Relevant log output

```shell
-
```
